### ISSUE TITLE
User scroll(horizontal) fast, right or left only one month only move but now this library is moving more than month

### ISSUE THREAD

**Issue by FrancisRR** [wdullaer/MaterialDateTimePicker#583] opened 2019-04-18 13:02 UTC
In this sample project not used in the library, your directly used in default android date picker.

 view.findViewById(R.id.original_button).setOnClickListener(v -> {
            Calendar now = Calendar.getInstance();
            **new android.app.DatePickerDialog**(
                    requireActivity(),
                    (view1, year, month, dayOfMonth) -> Log.d("Orignal", "Got clicked"),
                    now.get(Calendar.YEAR),
                    now.get(Calendar.MONTH),
                    now.get(Calendar.DAY_OF_MONTH)
            ).show();
        });

Picker**(DatePickerFragment)**

In this library, if I scroll fast to right or left in horizontal then it will be move in 3 or 4 months but default date picker only move in one month only.

Please let me know how to solve this issue(user horizontal scroll fast, right or left only one month only move)

**Comment by wdullaer** [comment] 2019-04-18 17:49
Duplicate of #514

**Closed by wdullaer** 2019-04-18 17:49 UTC
