### ISSUE TITLE
Date picker style like in Google design guidelines

### ISSUE THREAD

**Issue by Nitnatsnok** [wdullaer/MaterialDateTimePicker#89] opened 2015-09-09 13:20 UTC
Hello,
Is it possible to make date picker look like this:
![components_pickers_date1](https://cloud.githubusercontent.com/assets/8686045/9762769/4d744854-570e-11e5-8f0f-63f82be4edbe.png)

Or advise a suitable library, please.

Thank you for your work, and sorry for my bad english.

**Comment by wdullaer** [comment] 2015-09-10 18:44
This is a duplicate of #27 

I intend to implement the new design at some point, but due to time constraints it won't be any time soon.

**Closed by wdullaer** 2015-09-10 18:44 UTC
