### ISSUE TITLE
You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by yanbing177** [wdullaer/MaterialDateTimePicker#51] opened 2015-07-02 15:33 UTC
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

compileSdkVersion 22
    buildToolsVersion "22.0.1"

**Comment by enriqif** [comment] 2015-07-02 16:01
hey yanbing177 recently I had the same problem and I resolve changing the theme in the styles.xml file in your project, I guess that you activity extends from AppCompatActivity.., try  to change that with another theme like Theme.AppCompat in my file i have right now this lines..

`<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">`
`          <item name="colorPrimary">@color/colorPrimary</item>`
`          <item name="colorPrimaryDark">@color/colorPrimaryDark</item>`
`          <item name="windowActionBar">false</item>`
`          <item name="windowNoTitle">true</item>`
`</style>`

and in your AndroidiManifest.xml you have to reference to that style declared

`<application `
`      	android:allowBackup="true"`
`        android:icon="@drawable/ic_launcher"`
`       android:label="@string/app_name"`
`        android:theme="@style/AppTheme">`

hope you be useful..

**Comment by wdullaer** [comment] 2015-07-03 09:43
@enriqif is right, you are probably using AppCompatActivity.
This library explicitly does not depend on AppCompat for this reason.

I'm closing this as it is not a bug in this library.

**Closed by wdullaer** 2015-07-03 09:43 UTC
