### ISSUE TITLE
 java.lang.RuntimeException: Parcelable encountered IOException writing serializable object

### ISSUE THREAD

**Issue by Samadhan-Medge** [wdullaer/MaterialDateTimePicker#358] opened 2017-05-29 09:27 UTC
Getting below issue when datepicker is open and recent app button get pressed
```
FATAL EXCEPTION: main
                   Process: ae.tameen.myoic, PID: 27138
                   java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.wdullaer.materialdatetimepicker.date.DefaultDateRangeLimiter)
                       at android.os.Parcel.writeSerializable(Parcel.java:1388)
                       at android.os.Parcel.writeValue(Parcel.java:1335)
                       at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
                       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
                       at android.os.Bundle.writeToParcel(Bundle.java:1096)
                       at android.os.Parcel.writeBundle(Parcel.java:663)
                       at android.app.FragmentState.writeToParcel(Fragment.java:139)
                       at android.os.Parcel.writeTypedArray(Parcel.java:1191)
                       at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:376)
                       at android.os.Parcel.writeParcelable(Parcel.java:1357)
                       at android.os.Parcel.writeValue(Parcel.java:1262)
                       at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
                       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
                       at android.os.Bundle.writeToParcel(Bundle.java:1096)
                       at android.os.Parcel.writeBundle(Parcel.java:663)
                       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3029)
                       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3460)
                       at android.os.Handler.handleCallback(Handler.java:739)
                       at android.os.Handler.dispatchMessage(Handler.java:95)
                       at android.os.Looper.loop(Looper.java:135)
                       at android.app.ActivityThread.main(ActivityThread.java:5536)
                       at java.lang.reflect.Method.invoke(Native Method)
                       at java.lang.reflect.Method.invoke(Method.java:372)
                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1397)
                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1192)
                    Caused by: java.io.NotSerializableException: com.wdullaer.materialdatetimepicker.date.DatePickerDialog
                       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
                       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                       at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
                       at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
                       at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
                       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
                       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                       at android.os.Parcel.writeSerializable(Parcel.java:1383)
                       at android.os.Parcel.writeValue(Parcel.java:1335) 
                       at android.os.Parcel.writeArrayMapInternal(Parcel.java:638) 
                       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313) 
                       at android.os.Bundle.writeToParcel(Bundle.java:1096) 
                       at android.os.Parcel.writeBundle(Parcel.java:663) 
                       at android.app.FragmentState.writeToParcel(Fragment.java:139) 
                       at android.os.Parcel.writeTypedArray(Parcel.java:1191) 
                       at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:376) 
                       at android.os.Parcel.writeParcelable(Parcel.java:1357) 
                       at android.os.Parcel.writeValue(Parcel.java:1262) 
                       at android.os.Parcel.writeArrayMapInternal(Parcel.java:638) 
                       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313) 
                       at android.os.Bundle.writeToParcel(Bundle.java:1096) 
                       at android.os.Parcel.writeBundle(Parcel.java:663) 
                       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3029) 
                       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3460) 
                       at android.os.Handler.handleCallback(Handler.java:739) 
                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                       at android.os.Looper.loop(Looper.java:135) 
                       at android.app.ActivityThread.main(ActivityThread.java:5536) 
                       at java.lang.reflect.Method.invoke(Native Method) 
                       at java.lang.reflect.Method.invoke(Method.java:372) 
                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1397) 
                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1192) 
```

**Comment by wdullaer** [comment] 2017-05-29 09:48
Duplicate of #349 
This has been resolved in the latest version of this library

**Closed by wdullaer** 2017-05-29 09:48 UTC
Labels: duplicate
