### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException

### ISSUE THREAD

**Issue by DarKane86** [wdullaer/MaterialDateTimePicker#368] opened 2017-06-10 16:48 UTC
Sometimes i have this exception on DefaultDateRangeLimiter
Some object isn't serializable and causes this exception

Fatal Exception: java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.virail.views.materialdatetimepicker.date.DefaultDateRangeLimiter)
       at android.os.Parcel.writeSerializable(Parcel.java:1447)
       at android.os.Parcel.writeValue(Parcel.java:1395)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:665)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1337)
       at android.os.Bundle.writeToParcel(Bundle.java:1079)
       at android.os.Parcel.writeBundle(Parcel.java:690)
       at android.app.FragmentState.writeToParcel(Fragment.java:142)
       at android.os.Parcel.writeTypedArray(Parcel.java:1233)
       at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:381)
       at android.os.Parcel.writeParcelable(Parcel.java:1416)
       at android.os.Parcel.writeValue(Parcel.java:1322)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:665)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1337)
       at android.os.Bundle.writeToParcel(Bundle.java:1079)
       at android.os.Parcel.writeBundle(Parcel.java:690)
       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3153)
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3455)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5621)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by wdullaer** [comment] 2017-06-10 18:26
Duplicate of #349
This has been resolved in the latest version of this library

**Closed by wdullaer** 2017-06-10 18:26 UTC
Labels: duplicate
