### ISSUE TITLE
Wrong month

### ISSUE THREAD

**Issue by hearsilent** [wdullaer/MaterialDateTimePicker#57] opened 2015-07-12 18:56 UTC
![Wrong month](https://cloud.githubusercontent.com/assets/5742579/8639376/b427db74-290a-11e5-95cb-0dea04aac675.png)

**Comment by wdullaer** [comment] 2015-07-12 19:24
Duplicate of #44 

I can't reproduce this, so a code sample or instructions on how to reliably trigger this behaviour are much appreciated.

**Closed by wdullaer** 2015-07-12 19:24 UTC

**Comment by hearsilent** [comment] 2015-07-12 19:54
I found the bud is  occurred by timezone.
If I set the timezone is +8, then it will show the wrong month.

**Comment by hearsilent** [comment] 2015-07-15 15:33
https://github.com/wdullaer/MaterialDateTimePicker/pull/58
