### ISSUE TITLE
Override accent colors

### ISSUE THREAD

**Issue by Vojtas87** [wdullaer/MaterialDateTimePicker#181] opened 2016-03-07 14:54 UTC
Hello, I've got a similar problem like #170. On my 5.1.1 if I let your original color, everything is fine. I tried to override color in colors.xml, then in values.xml - no success. But when I set my own accent color, some strange color appears. For example when I set blue color, so the result is purple color. Isn't there some transparency set?

**Comment by Johnsonmaung** [comment] 2016-03-11 07:09
me too. My custom color is also pale blue..

**Comment by Vojtas87** [comment] 2016-03-11 07:28
I tried some other ways and this (deprecated) representation works for me:
dpd.setAccentColor(getResources().getColor(R.color.mdtp_accent_color));

**Comment by Johnsonmaung** [comment] 2016-03-11 07:43
![screen shot 2016-03-11 at 2 10 27 pm](https://cloud.githubusercontent.com/assets/14939049/13696214/32e5dcbc-e793-11e5-804c-b059091531a4.png)

Correct or not.. I got with this. =D
dpd.setAccentColor(Color.parseColor("#2c3691"));

**Comment by wdullaer** [comment] 2016-03-14 16:53
It would be helpful if you could show me the code snippet where you actually set the color and how the color value is computed.

Given that the method just takes an `int` which in android can be any number of things, I'm thinking that the colors are not supplied correctly.
Once I know how it's failing, I can add some additional input validation or better documentation.

**Comment by vikramkakkar** [comment] 2016-03-15 03:39
> Given that the method just takes an `int` which in android can be any number of things, I'm thinking that the colors are not supplied correctly.

You can use annotations to make the argument(s) values quite specific:

    /**
     * Set the accent color of this dialog
     * @param accentColor the accent color you want
     */
    public void setAccentColor(@ColorInt accentColor) {
        mAccentColor = accentColor;
    }

For most, this confusion will be resolved by looking at the source code, for example, this line:
 
    // confirms that mAccentColor is @ColorInt
    view.findViewById(R.id.day_picker_selected_date_layout).setBackgroundColor(mAccentColor);

But, for the rest (dare I say, _uninitiated_), annotations help clear things up.

**Comment by wdullaer** [comment] 2016-03-15 07:49
That was the plan: annotate in the code and improve the docs.

I'd like to be sure that this is indeed the cause for everyone's issues though (there's a lot of issues around this)

**Comment by vikramkakkar** [comment] 2016-03-15 15:05
@Vojtas87 Consider posting a screenshot, and the values set by you. 

#170 has been resolved. But, I doubt that you're having the same issue (awesome, if you are :) ).

**Closed** 2016-03-17 20:21 UTC
