### ISSUE TITLE
Disable To on Date and Time Dialog

### ISSUE THREAD

**Issue by tux-world** [wdullaer/MaterialDateTimePicker#214] opened 2016-07-11 11:38 UTC
Hi, how can i disable TO from date and time picker? i dont need to have that,

Thanks

**Comment by wdullaer** [comment] 2016-07-11 17:35
By fixing your dependencies and actually using this library rather than https://github.com/borax12/MaterialDateRangePicker

Duplicate of #151

**Closed by wdullaer** 2016-07-11 17:35 UTC
Labels: duplicate, invalid

**Comment by tux-world** [comment] 2016-07-11 18:31
@wdullaer Thanks, but whats dependency? i'm using ``` compile 'com.borax12.materialdaterangepicker:library:1.6' ```

**Comment by wdullaer** [comment] 2016-07-11 18:32
It's more or less the first thing in the README on the homepage of this github project
