### ISSUE TITLE
Landscape mode UI

### ISSUE THREAD

**Issue by nowke** [wdullaer/MaterialDateTimePicker#62] opened 2015-07-15 16:46 UTC
Is it possible to add an option for Landscape UI as mentioned in Google Design Spec?

![Landscape Date Picker](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B3321sZLoP_Hamc5d1k2SmhlV2c/components_pickers_date3.png)

![Landscape Time Picker](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B3321sZLoP_HREpvc2hIX210OVE/components_pickers_time2.png)

**Comment by wdullaer** [comment] 2015-07-16 15:43
This request is similar to #27 
Google updated the design of both the portrait and landscape pickers. I haven't had time yet to implement them.
I'm not sure if I'll make these an option on the current one's or separate widgets.

Google also hasn't updated the design of the pickers in android to this design yet. So using these now will actually make your pickers feel out of place.

This will rank higher on the priority ladder once google implements it themselves in some app.

**Comment by wdullaer** [comment] 2015-07-19 19:02
I think I've figured out how to support both versions of the picker layout without too much hassle.
It should also solve something which has bugged me for a long time in the landscape timepicker.

Now I just need to find myself some time to do it.

**Comment by masztalski** [comment] 2015-07-24 09:16
I tested corrected landscape mode of calendar on Lenovo A800 and although it is better than in 1.3.0 still doesn't fully correct. I attach view in portrait and in landscape mode:
![screenshot_2015-07-24-11-11-58](https://cloud.githubusercontent.com/assets/11578875/8871426/6a6186f4-31f5-11e5-9257-5adac4290afa.png)
![screenshot_2015-07-24-11-12-13](https://cloud.githubusercontent.com/assets/11578875/8871425/6a6117d2-31f5-11e5-9236-1a2620f397ad.png)

**Comment by wdullaer** [comment] 2015-07-24 11:21
Can you create a new issue for this?

The wrong coloring seems like a bug.
The vertical spacing, I'll need to take a closer look at.

**Comment by masztalski** [comment] 2015-07-24 11:28
ok, Issue created. I don't know what you mean about wrong coloring, because I have overwrite some settings. Or do you mean wrong background for day of week in landscape layout?

**Comment by wdullaer** [comment] 2015-07-24 12:15
yes that one.

If you've overwritten it, then well, it's by design I guess :-)

**Comment by masztalski** [comment] 2015-07-24 12:26
I have overwrriten:
    <color name="mdtp_accent_color">#ff646f7d</color>
    <color name="mdtp_button_color">#24AFB2</color>

background of day of week wasn't touched(sincerely I have no idea which parameter this could be ;) )

**Comment by wdullaer** [comment] 2016-11-20 11:25
Fixed in version 3.0.0

**Closed** 2016-11-20 11:25 UTC
Labels: enhancement
