### ISSUE TITLE
Set custom locale

### ISSUE THREAD

**Issue by davidvavra** [wdullaer/MaterialDateTimePicker#359] opened 2017-05-30 19:48 UTC
Hi, the date picker is always using a default locale. That's not always desirable. We support only a few languages and for unsupported languages we would like to show English date picker, because rest of the app is also in English. Do you think you can support custom locales?

**Comment by wdullaer** [comment] 2017-05-31 10:05
Duplicate of #325 
It's on the backlog, but I have no idea how to properly handle this right now

**Closed by wdullaer** 2017-05-31 10:05 UTC

**Comment by davidvavra** [comment] 2017-05-31 10:37
I have looked into the code, it shouldn't be too hard. Just replace Locale.getDefault() in the code with a variable which is customisable (default locale by default).
