### ISSUE TITLE
BUG: Incorrect calendar month

### ISSUE THREAD

**Issue by TakumaMochizuki** [wdullaer/MaterialDateTimePicker#44] opened 2015-06-14 17:13 UTC
Like this, how can I fix it in this 1.3.1 version?
e.g.
![Imgur](http://i.imgur.com/NRLuUlM.png)

**Comment by wdullaer** [comment] 2015-06-14 18:05
I need some code to reproduce this.

What locale is your device in?
What is the date that's returned when you press ok (does it return May or June in the above example)?

**Comment by TakumaMochizuki** [comment] 2015-06-15 15:20
I retry one more time, and now is correct. But I don't change anything.

The code is from sample code, and my locale on emulator and zh-TW, and they are the same problem, but now all clear......

And I can't reappear the same situation now......sorry...

and the code 
```
Calendar now = Calendar.getInstance();
        DatePickerDialog datePickerDialog = DatePickerDialog.newInstance(this,
                now.get(Calendar.YEAR),
                now.get(Calendar.MONTH),
                now.get(Calendar.DAY_OF_MONTH));
        datePickerDialog.show(getActivity().getFragmentManager(), "DPD");
```

**Comment by wdullaer** [comment] 2015-06-15 17:57
No worries.
Thanks for reporting it.
I'll close the issue for now. If you manage to reproduce this, please post a code sample and reopen the ticket.

**Comment by nodegin** [comment] 2015-07-07 17:16
I got same issue..

**Comment by wdullaer** [comment] 2015-07-07 18:33
Be that as it may, I cannot reproduce this.
I need a code sample that reliably reproduces this issue on any device, otherwise I can't figure out what is going on.

**Comment by nodegin** [comment] 2015-07-08 08:16
My code is same as example

**Comment by TakumaMochizuki** [comment] 2015-07-08 09:01
I found this issue occurred in debug mode in my case.
And stop debugging, it will be correct.

**Closed** 2015-07-19 18:48 UTC
Labels: bug
