### ISSUE TITLE
Date Picker Done Button Text Truncated on Emulator

### ISSUE THREAD

**Issue by josh7up** [wdullaer/MaterialDateTimePicker#2] opened 2015-02-06 22:13 UTC
When displaying the DatePickerDialog on an emulator on OS X Yosemite, the "DONE" text is cutoff on the bottom (see screenshot):

![date picker done button truncated](https://cloud.githubusercontent.com/assets/2333968/6088319/0e22dfd8-ae23-11e4-8e7b-3c911540b753.png)

**Comment by wdullaer** [comment] 2015-02-11 21:07
I can't reproduce it here.
Are you seeing this on devices as well?

**Comment by KarimaEngineer** [comment] 2015-03-04 12:11
I want to set the minutes only each 15 min and even the movement of the selector so should I modify only RadialPickerLayout ?

**Comment by wdullaer** [comment] 2015-03-04 19:39
RadialSelectorView would be the place to look.

If you have an issue, you should create a new issue and not use an existing one.
For questions, like this one, I think stackexchange is your best bet.

**Comment by josh7up** [comment] 2015-03-04 20:05
So far, I have only seen this issue on the emulator and not on devices. I wouldn't consider this critical by any means, but I just wanted to point out that this exists for me on the emulator. Great library!

**Comment by wdullaer** [comment] 2015-03-04 20:28
Because I plan to replace that done button with a material themed "OK" button at some point, I'll close the issue for now. If someone encounters this on a device, please reopen.

@josh7up Thanks for the praise :-)

**Closed by wdullaer** 2015-03-04 20:28 UTC
