### ISSUE TITLE
Only month and Year in DatePicker

### ISSUE THREAD

**Issue by toannm0802** [wdullaer/MaterialDateTimePicker#197] opened 2016-04-20 09:12 UTC
Hi, 

It is possible to have only month and year picker because im develop an app not require day picker?

Thanks!

**Comment by wdullaer** [comment] 2016-04-22 20:14
Duplicate of #5 
The design of the daypicker doesn't lend itself to just month and years, it's not a usecase I intend to support right now.

**Closed by wdullaer** 2016-04-22 20:14 UTC
Labels: duplicate
