### ISSUE TITLE
Can't apply in Fragment . Please help .

### ISSUE THREAD

**Issue by dalwadi2** [wdullaer/MaterialDateTimePicker#154] opened 2016-01-29 13:34 UTC
I use fragment for regestration so I face problem in this lines. please reply me is this correct or not ?

```

DatePickerDialog dpd = DatePickerDialog.newInstance(
                (DatePickerDialog.OnDateSetListener) getActivity(),
                now.get(Calendar.YEAR),
                now.get(Calendar.MONTH),
                now.get(Calendar.DAY_OF_MONTH)
        );
```

And suggest That what i have to write here :

`dpd.show(fm, "Datepickerdialog");`

**Comment by wdullaer** [comment] 2016-02-13 01:51
Take a look at the included sample application.

Are you getting any specific errors?

**Comment by amineghabi** [comment] 2016-02-15 14:00
me too I have problem in my my fragment !! how to solve it ?

**Comment by amineghabi** [comment] 2016-02-16 11:03
that's not proffesionnal , try to fix the problem !! why you close this issue ?

**Comment by ismdcf** [comment] 2016-03-28 14:26
Having the same problem, Why is the issue closed without resolving it

**Comment by dalwadi2** [comment] 2016-03-28 14:36
Okay, no problem .
I changed picker because I had urgent requirement so.
you can stay on this issue .
@wdullaer please help to solve this issue ASAP .

**Comment by wdullaer** [comment] 2016-03-28 14:39
I can't reproduce this issue, and none of the posts contain any relevant information.

Unless one of you stops complaining and actually answers the questions I've asked or comes up with a reliable way to reproduce this issue, I will close it again in 5 days.

**Comment by putraxor** [comment] 2016-03-28 19:34
You have to change your code to:

`DatePickerDialog dpd = DatePickerDialog.newInstance(
                **a_fragment_manager**,
                now.get(Calendar.YEAR),
                now.get(Calendar.MONTH),
                now.get(Calendar.DAY_OF_MONTH)
        );`

I also have this problem, but this library seems not supporting instantiate from Android Support FragmentManager, is it right @wdullaer ?

**Comment by dalwadi2** [comment] 2016-03-29 05:17
@amineghabi @ismdcf when you get answer close this issue or tell to close !

**Comment by ajaygolu94** [comment] 2016-04-27 02:39
Try this code, it is worked for me...  

                    
                        Calendar now = Calendar.getInstance();
                        DatePickerDialog dpd = DatePickerDialog.newInstance(
                                new DatePickerDialog.OnDateSetListener() {
                                    @Override
                                    public void onDateSet(DatePickerDialog view, int year, int monthOfYear, int                               dayOfMonth) {

                                    }
                                },
                                now.get(Calendar.YEAR),
                                now.get(Calendar.MONTH),
                                now.get(Calendar.DAY_OF_MONTH)
                        );

                        /* Convert you context to an activity to get Fragment Manager */
                        final Activity activity = (Activity) context;
                        dpd.show(activity.getFragmentManager(), "Datepickerdialog");

**Comment by samk17cmutpm** [comment] 2016-05-30 04:16
You can directly call

getFragmentManager() 
to get the fragment manager.

or

In your fragment,

Create field :

private FragmentActivity myContext;
override onAttach method of your fragment :

@Override 
public void onAttach(Activity activity) {
    myContext=(FragmentActivity) activity;
    super.onAttach(activity);
} 
When you need to get Support fragment manager call :

FragmentManager fragManager = myContext.getSupportFragmentManager(); //If using fragments from support v4
or

FragmentManager fragManager = myContext.getFragmentManager();

**Comment by SilentThunder89** [comment] 2017-02-05 14:48
`dpd.show(getActivity().getFragmentManager(), "tag");`
works for me

to reproduce have your fragment class import android.support.v4.app.Fragment instead of android.app.Fragment

**Closed** 2017-02-06 13:17 UTC
Labels: question
