### ISSUE TITLE
DefaultDateRangeLimiter not Serializable

### ISSUE THREAD

**Issue by laalto** [wdullaer/MaterialDateTimePicker#351] opened 2017-05-10 11:36 UTC
Observing crashes when sending an app to background when `DatePickerDialog` is active and the platform is writing the DialogFragment to a Bundle while storing fragment backstack state. Stacktrace:

```
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.wdullaer.materialdatetimepicker.date.g)
	at android.os.Parcel.writeSerializable(Parcel.java:1527)
	at android.os.Parcel.writeValue(Parcel.java:1475)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:724)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1408)
	at android.os.Bundle.writeToParcel(Bundle.java:1157)
	at android.os.Parcel.writeBundle(Parcel.java:764)
	at android.app.FragmentState.writeToParcel(FragmentState.java:149)
	at android.os.Parcel.writeTypedArray(Parcel.java:1307)
	at android.app.FragmentManagerState.writeToParcel(FragmentManagerState.java:381)
	at android.os.Parcel.writeParcelable(Parcel.java:1496)
	at android.os.Parcel.writeValue(Parcel.java:1402)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:724)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1408)
	at android.os.Bundle.writeToParcel(Bundle.java:1157)
	at android.os.Parcel.writeBundle(Parcel.java:764)
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerProxy.java:3841)
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3917)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6290)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.io.NotSerializableException: com.wdullaer.materialdatetimepicker.date.b
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1224)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1584)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1549)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
	at android.os.Parcel.writeSerializable(Parcel.java:1522)
	... 23 more
```

(Unobfuscation: `.g` is `.DefaultDateRangeLimiter`, `.b` is `.DatePickerDialog`.)

Reading the source it seems that the next field in `DatePickerDialog` i.e. `HapticFeedbackController mHapticFeedbackController` would fail serialization in a case like this.

**Comment by wdullaer** [comment] 2017-05-10 12:31
Thanks for the detailed report.
This is a duplicate of #349 (I'll close this one in favor of the other)

I doubt the root cause is the `HapticFeedbackController`. This started after I introduced the `DefaultDateRangeLimiter`, so that's a more likely place to start looking.
If you have any more information, please share :-)

**Closed by wdullaer** 2017-05-10 12:31 UTC
Labels: duplicate

**Comment by laalto** [comment] 2017-05-10 12:36
Thanks, tried looking up for existing bug report but the IOException did not seem relevant :)

**Comment by laalto** [comment] 2017-05-10 12:38
Yes it's the DefaultDateRangeLimiter that causes this stacktrace but might get another crash for the other field that seemed to be non-transient and non-serializable. Did not spend too much time reading the code though.

**Comment by burugular** [comment] 2018-02-12 22:55
Dismissing the Dialog resolved the crash.
```

private DatePickerDialog datePickerDialog;

@Override
    public void onPause() {
        super.onPause();
        datePickerDialog.dismiss();
    }
```
