### ISSUE TITLE
We need to support Android P.

### ISSUE THREAD

**Issue by kimok0508** [wdullaer/MaterialDateTimePicker#535] opened 2018-10-05 09:50 UTC
In Android P, Google deprecated native fragment api. So, We can not use fragmentManager anymore.

**Comment by wdullaer** [comment] 2018-10-08 07:56
Duplicate of #451 

I would also like to point out that you can still use any native fragment APIs in android P. They have been deprecated, not been removed.

**Closed by wdullaer** 2018-10-08 07:56 UTC
Labels: duplicate
