### ISSUE TITLE
Can not choose a day in month with 5 weeks

### ISSUE THREAD

**Issue by Vojtas87** [wdullaer/MaterialDateTimePicker#463] opened 2018-03-13 22:08 UTC
v3.5.1: If setScrollOrientation(DatePickerDialog.ScrollOrientation.VERTICAL) everything is OK.
v3.5.2: If setScrollOrientation(DatePickerDialog.ScrollOrientation.VERTICAL) there is some design change, so for now it is not possible to pick some days. For example in January there is 5 weeks. So how can I choose for example 31st of January? It is hidden and it can't be clicked. Thank you for your reply in advance.

**Comment by wdullaer** [comment] 2018-03-14 07:39
What device are you testing this on? Can you show a screen shot? 
This is working just fine for me here.

**Comment by Vojtas87** [comment] 2018-03-14 08:27
![date_picker](https://user-images.githubusercontent.com/17688308/37390842-a448d0f4-2769-11e8-8ded-9c9743d96e6a.png)
It appears on Samsung Galaxy S7. January 2017 is at my Czech locale. Sorry for partial informations. At English locale it is for example December 2017. See an attachement, please.

**Comment by wdullaer** [comment] 2018-03-14 18:46
Ok cheers, I reproduced it.

**Comment by ZeevoX** [comment] 2018-04-27 07:24
I assume I cannot pick April 30th 2018 because of this issue, and it isn't the app developer's code but instead this library that is causing the problem.

**Comment by wdullaer** [comment] 2018-04-27 09:17
If all goes well, I'll be able to release a version with a fix for this over the weekend.

**Closed** 2018-04-28 13:51 UTC
Labels: bug
