### ISSUE TITLE
Unexpected crash on API 16

### ISSUE THREAD

**Issue by nyayadhish20** [wdullaer/MaterialDateTimePicker#362] opened 2017-06-05 09:54 UTC
FATAL EXCEPTION: main
                                                            android.view.InflateException: Binary XML file line #37: Error inflating class TextView
                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                at android.view.LayoutInflater.parseInclude(LayoutInflater.java:830)
                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:736)
                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:318)
                                                                at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:829)
                                                                at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1035)
                                                                at android.app.BackStackRecord.run(BackStackRecord.java:635)
                                                                at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1397)
                                                                at android.app.FragmentManagerImpl$1.run(FragmentManager.java:426)
                                                                at android.os.Handler.handleCallback(Handler.java:615)
                                                                at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                at android.os.Looper.loop(Looper.java:137)
                                                                at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:511)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                at dalvik.system.NativeStart.main(Native Method)
                                                             Caused by: java.lang.ArrayIndexOutOfBoundsException: length=23; index=1194
                                                                at android.content.res.StringBlock.get(StringBlock.java:64)
                                                                at android.content.res.XmlBlock$Parser.getPooledString(XmlBlock.java:458)
                                                                at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:720)
                                                                at android.content.res.TypedArray.getString(TypedArray.java:124)
                                                                at android.widget.TextView.<init>(TextView.java:792)
                                                                at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)
                                                                at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:58)
                                                                at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
                                                                at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1029)
                                                                at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1087)
                                                                at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:675)
                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
                                                                at android.view.LayoutInflater.parseInclude(LayoutInflater.java:830) 
                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:736) 
                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:318) 
                                                                at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:829) 
                                                                at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1035) 
                                                                at android.app.BackStackRecord.run(BackStackRecord.java:635) 
                                                                at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1397) 
                                                                at android.app.FragmentManagerImpl$1.run(FragmentManager.java:426) 
                                                                at android.os.Handler.handleCallback(Handler.java:615) 
                                                                at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                                at android.os.Looper.loop(Looper.java:137) 
                                                                at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by wdullaer** [comment] 2017-06-05 19:35
This issue isn't very helpful to me.
There are absolutely no useful pointers in that stacktrace.

Can you create a small code sample with just this library that reliably reproduces the issue?

**Comment by asknask** [comment] 2017-07-20 13:21
Just faced this very issue on a 5.1.1 Samsung Galaxy Grand Prime. Exact same stack trace.

Issue isn't produced on a 6.0.1 Galaxy Note 4. What kinda details do you need? The stacktrace mentions DatePickerDialog Line 318 (which is the inflate line).

**Comment by asknask** [comment] 2017-07-25 12:05
I used the same version in another app and now it is crashing on the 6.0.1 Galaxy Note 4 as well. Only happens for the Date picker.

**Comment by wdullaer** [comment] 2017-07-28 09:04
Can you create a code sample that recreates the issue?
Which features of the DatePickerDialog are you using?
Do you have an idea which version introduced this bug?

**Comment by asknask** [comment] 2017-07-28 10:05
After some investigation, it has become apparent that this isn't an issue with the library but with a few specific Samsung phones. The crash on my Note 4 wasn't due to the same issue.

There has only been 1 phone that shows the behavior mentioned here (in my case) and that was a 5.0.1 Samsung Galaxy Grand Prime. I haven't been able to reproduce it on any other platforms, but I also haven't been able to find a workaround for it.

I believe it has something to do with Samsung using obsolete built-in support libs.

**Comment by wdullaer** [comment] 2017-07-28 12:35
The idea of the support lib is that it uses the versions shipped with the app, otherwise you can just use the native platform libraries.

If you would know which version introduced this crash, I could maybe try to triage the issue.
I don't like to leave issues like this hanging, but it's though if I don't have a reliable way to reproduce it.

In any case: thanks for the time you've spent on this.

**Comment by nyayadhish20** [comment] 2017-07-29 14:44
I am using 25.1.0 support library version. I got that crash on API 16

**Comment by asknask** [comment] 2017-07-29 19:58
In my app I'm on 25.3.1. But that might be irrelevant if the system is using some older Samsung-provided version.

How do I check which version my widget is using?

**Comment by wdullaer** [comment] 2017-10-29 15:47
Duplicate of #416 
I'll track progress on this in that issue

**Closed by wdullaer** 2017-10-29 15:47 UTC
Labels: user input required
