### ISSUE TITLE
Strange Issue with Maximum and Minimum Year Range

### ISSUE THREAD

**Issue by AngleV** [wdullaer/MaterialDateTimePicker#7] opened 2015-03-24 21:18 UTC
If i choose the year and scroll down to year 2050 after selecting it, the month shows wrong year... 
I change the maximum year to 2036 and it works ok but the same thing happens if i choose year below 1902.

Why is this happening ? 

Also when i set for a date the month has a one number down difference.  try to choose March of 2015. it returns 02 of 2015 and not 03.

**Comment by wdullaer** [comment] 2015-03-25 09:08
Hi, the month number is by design. The standard datepicker in Android uses zero based indexing for the month. I decided to stick to that convention, to keep the API similar.

Do you have screenshots of the first issue? I can't seem to reproduce it here.

**Comment by AngleV** [comment] 2015-03-25 12:12
So for the month we are ok since Android uses zero based indexing.

As for the second issue 
Steps to reproduce.

1. Tap Year
2. Scroll down to year 2050
3. Notice the year below in the Calendar

![device-2015-03-25-140008](https://cloud.githubusercontent.com/assets/7430985/6824107/8d17311a-d2f7-11e4-89d5-c4eea7266257.png)

it goes like this until year 2036. The same goes also if i choose year below 1902.
The issue seams to appear in Jellybean 4.1.1 since i tested in  4.4.4  and it works fine

**Comment by wdullaer** [comment] 2015-03-25 14:38
It looks like this is a bug in the underlying system libraries.
Time is represented as a long: the number of milliseconds since the epoch, which somewhere in the 1970s. Dates before that are negative. It looks like the internal representation overflows and wraps around.

I'll see if I can find some bug reports on this and figure out in which version of android this could have been fixed.
I cannot reproduce it on Android 4.4

**Comment by AngleV** [comment] 2015-03-25 23:45
Yes in Android 4.4 and above it seems to work fine.

**Comment by wdullaer** [comment] 2015-03-28 18:32
The picker in the android calendar app (on which this one is based), just limits the year selection to the range where the rendering actually works (1970 - 2036).
You can use the `setMinDate(Calendar c)`and `setMaxDate(Calendar c)` values to accomplish this.

I'm going to close this as a wontfix for the moment, but feel free to re-open it if you've found a good solution.

**Closed by wdullaer** 2015-03-28 18:33 UTC
Labels: wontfix
