### ISSUE TITLE
Migrate to support libs / `SupportDialogFragment`

### ISSUE THREAD

**Issue by masc3d** [wdullaer/MaterialDateTimePicker#527] opened 2018-09-18 07:03 UTC
as anything that does not use compat / support lib will be deprecated (including `DialogFragment`).
https://developer.android.com/reference/android/app/DialogFragment

**Comment by wdullaer** [comment] 2018-09-20 14:07
Duplicate of #451

**Closed by wdullaer** 2018-09-20 14:07 UTC
Labels: duplicate
