### ISSUE TITLE
Android API 28 depracates FragmentManager and DialogFragment

### ISSUE THREAD

**Issue by snowb1shop** [wdullaer/MaterialDateTimePicker#494] opened 2018-06-08 12:15 UTC
MaterialDatePicker should extend android.support.v4.app.DialogFragment not android.app.DialogFragment, due to the Android P API changes.

**Comment by wdullaer** [comment] 2018-06-08 15:03
Duplicate of #451

**Closed by wdullaer** 2018-06-08 15:03 UTC
Labels: duplicate
